aspnetcore/Api.Test/Api.Test.csproj
aspnetcore/Api.Test/ApiIntegrationTest.cs
aspnetcore/Api.Test/TestWebApplicationFactory.cs
aspnetcore/Api.Test/appsettings.Development.json
aspnetcore/Api.Test/appsettings.json
aspnetcore/PublicApi.sln
aspnetcore/src/Api/Api.csproj
aspnetcore/src/Api/ConfigurationExtensions/ElasticSearchExtensions.cs
aspnetcore/src/Api/Controllers/FundingCallController.cs
aspnetcore/src/Api/Controllers/FundingDecisionController.cs
aspnetcore/src/Api/Controllers/PublicationController.cs
aspnetcore/src/Api/Models/FundingCall.cs
aspnetcore/src/Api/Models/FundingCall/Category.cs
aspnetcore/src/Api/Models/FundingCall/Foundation.cs
aspnetcore/src/Api/Models/FundingCall/FundingCall.cs
aspnetcore/src/Api/Models/FundingCall/FundingCallSearchParameters.cs
aspnetcore/src/Api/Models/FundingDecision.cs
aspnetcore/src/Api/Models/FundingDecisionSearchParameters.cs
aspnetcore/src/Api/Models/PublicationSearchParameters.cs
aspnetcore/src/Api/Program.cs
aspnetcore/src/Api/Services/ElasticSearchService.cs
aspnetcore/src/Api/Services/FundingCallQueryGenerator.cs
aspnetcore/src/Api/Services/IQueryGenerator.cs
aspnetcore/src/Api/Services/ISearchService.cs
aspnetcore/src/Api/Services/PublicationQueryGenerator.cs

Added FundingCallController with three search parameters and most of the search response fields.  More response fields and search parameter coming later.
Added basic integration tests for FundingCallController. The tests currently need local elasticsearch instance with hard-coded data to work, will be configured further later on.
Added FundingDecisionController (WIP) without functionality.

Added FundingCall controller with basic functionality

---

aspnetcore/src/Api/DatabaseContext/ApiDbContext.cs
aspnetcore/src/ElasticSearchIndexer/Indexer.cs
aspnetcore/src/ElasticSearchIndexer/Program.cs

DimCallProgramme's "continuos_application _period" renamed to "continuos_application_period"

Updated db context.

---

aspnetcore/src/Api.Test/FundingCallRepositorySystemTest.cs
aspnetcore/src/Api.Test/FundingDecisionRepositorySystemTest.cs
aspnetcore/src/Api.Test/InfrastructureSystemTest.cs
aspnetcore/src/Api.Test/appsettings.json
aspnetcore/src/Api/ApiPolicies.cs
aspnetcore/src/Api/ConfigurationExtensions/DataAccessExtensions.cs
aspnetcore/src/Api/Controllers/InfrastructureController.cs
aspnetcore/src/Api/DataAccess/Repositories/InfrastructureIndexRepository.cs
aspnetcore/src/Api/Maps/InfrastructureProfile.cs
aspnetcore/src/Api/Models/Infrastructure/Infrastructure.cs
aspnetcore/src/Api/Models/Infrastructure/InfrastructureSearchParameters.cs
aspnetcore/src/Api/Program.cs
aspnetcore/src/Api/Services/ElasticSearchQueryGenerators/InfrastructureQueryGenerator.cs
aspnetcore/src/Api/appsettings.json
aspnetcore/src/ElasticSearchIndexer/Indexer.cs

Added basic implementation for Infrastucture controller and indexing.

Infrastructures

---

aspnetcore/src/Api.Test/OrganizationSystemTest.cs
aspnetcore/src/Api.Test/appsettings.json
aspnetcore/src/Api/Api.csproj
aspnetcore/src/Api/ApiPolicies.cs
aspnetcore/src/Api/ConfigurationExtensions/DataAccessExtensions.cs
aspnetcore/src/Api/Controllers/OrganizationController.cs
aspnetcore/src/Api/Controllers/PublicationController.cs
aspnetcore/src/Api/DataAccess/Repositories/OrganizationIndexRepository.cs
aspnetcore/src/Api/Maps/OrganizationProfile.cs
aspnetcore/src/Api/Models/Organization/Organization.cs
aspnetcore/src/Api/Models/Organization/OrganizationSearchParameters.cs
aspnetcore/src/Api/Models/Publication/Author.cs
aspnetcore/src/Api/Models/Publication/FieldOfEducation.cs
aspnetcore/src/Api/Models/Publication/FieldOfScience.cs
aspnetcore/src/Api/Models/Publication/Organization.cs
aspnetcore/src/Api/Models/Publication/OrganizationUnit.cs
aspnetcore/src/Api/Models/Publication/ParentPublicationType.cs
aspnetcore/src/Api/Models/Publication/PeerReviewed.cs
aspnetcore/src/Api/Models/Publication/Person.cs
aspnetcore/src/Api/Models/Publication/Publication.cs
aspnetcore/src/Api/Models/Publication/PublicationSearchParameters.cs
aspnetcore/src/Api/Models/Publication/SelfArchived.cs
aspnetcore/src/Api/Models/Publication/SelfArchivedData.cs
aspnetcore/src/Api/Program.cs
aspnetcore/src/Api/Services/ElasticSearchQueryGenerators/OrganizationQueryGenerator.cs
aspnetcore/src/Api/Services/ElasticSearchQueryGenerators/PublicationQueryGenerator.cs
aspnetcore/src/Api/appsettings.json
aspnetcore/src/ElasticSearchIndexer/Indexer.cs

Basic implementation of Organization search.

Organizations

---

aspnetcore/openshift/indexer/template-indexer-pilot.yml
aspnetcore/src/Api/Services/ElasticSearchIndexService.cs
aspnetcore/src/Api/appsettings.Development.json
aspnetcore/src/Api/appsettings.json

Merge index name config changes to dev

Merge Pilot -> Dev

---

aspnetcore/PublicApi.sln
aspnetcore/openshift/indexer/template-indexer-devel.yml
aspnetcore/openshift/indexer/template-indexer-manualjob-devel.yml

Moved the manual indexing job to it's own template file.

Added indexing cronjob for devel template. 

---

aspnetcore/openshift/indexer/template-indexer-devel.yml
aspnetcore/src/Indexer/Properties/launchSettings.json
aspnetcore/src/Interface/Services/InfrastructureService.cs
aspnetcore/src/Interface/Services/PublicationService.cs
aspnetcore/src/Interface/Services/ResearchDatasetService.cs
aspnetcore/src/Interface/appsettings.Development.json

Fixes inadvertant problems caused by the previous task.
CSCTTV-2834, CSCTTV-2830

CSCTTV-2834: fix errors in namespaces preventing startup

---

aspnetcore/openshift/indexer/Dockerfile

CSCTTV-2850: update indexer dockerfile to the current project structure

---

aspnetcore/src/Interface/Maps/FundingDecisionProfile.cs

CSCTTV-2649 fix map

---

aspnetcore/src/ElasticService/ElasticSearchQueryGenerators/FundingCallQueryGenerator.cs
aspnetcore/src/ElasticService/ElasticSearchQueryGenerators/FundingDecisionQueryGenerator.cs
aspnetcore/src/ElasticService/ElasticSearchQueryGenerators/ResearchDatasetQueryGenerator.cs
aspnetcore/src/ElasticService/SearchParameters/FundingCallSearchParameters.cs
aspnetcore/src/Interface/Interface.csproj
aspnetcore/src/Interface/Models/FundingCall/FundingCall.cs
aspnetcore/src/Interface/Models/FundingDecision/Funder.cs
aspnetcore/src/Interface/Models/FundingDecision/FundingDecision.cs
aspnetcore/src/Interface/Models/FundingDecision/FundingGroupPerson.cs
aspnetcore/src/Interface/Models/FundingDecision/FundingType.cs
aspnetcore/src/Interface/Models/FundingDecision/Geo.cs
aspnetcore/src/Interface/Models/FundingDecision/Id.cs
aspnetcore/src/Interface/Models/FundingDecision/OrganizationConsortium.cs
aspnetcore/src/Interface/Models/FundingDecision/Topic.cs
aspnetcore/src/Interface/Models/GetFundingCallQueryParameters.cs
aspnetcore/src/Interface/Models/GetFundingDecisionQueryParameters.cs
aspnetcore/src/Interface/Models/GetResearchDatasetsQueryParameters.cs
aspnetcore/src/Service.Models/FundingDecision/Funder.cs
aspnetcore/src/Service.Models/FundingDecision/FundingDecision.cs
aspnetcore/src/Service.Models/FundingDecision/FundingGroupPerson.cs
aspnetcore/src/Service.Models/FundingDecision/OrganizationConsortium.cs

Add comments to funding call, funding decision and research dataset search parameters
Additionally refactored funding decision indexing and query generation to be more efficient

CSCTTV-2649 add comments for search parameters

---

aspnetcore/src/DatabaseContext/ApiDbContext.cs
aspnetcore/src/DatabaseContext/Entities/DimFieldOfScience.cs
aspnetcore/src/DatabaseContext/Entities/DimFundingDecision.cs
aspnetcore/src/DatabaseContext/Entities/DimPublication.cs
aspnetcore/src/Repositories/Maps/FundingDecisionProfile.cs
aspnetcore/test/Indexer.Tests/Maps/FundingDecisionProfileTest.cs

…decisions and publications
CSCTTV-3065

CSCTTV-3065 funding decision field of science structure change

---

aspnetcore/PublicApi.sln
aspnetcore/openshift/api/template-api-production.yml
aspnetcore/openshift/api/template-api-qa.yml
aspnetcore/openshift/indexer/template-indexer-manualjob-production.yml
aspnetcore/openshift/indexer/template-indexer-manualjob-qa.yml
aspnetcore/openshift/indexer/template-indexer-production.yml
aspnetcore/openshift/indexer/template-indexer-qa.yml

Add OpenShift templates for QA and production

Add OpenShift templates for QA and production

---

aspnetcore/src/Indexer/Indexer.cs
aspnetcore/src/Interface/Maps/FundingDecisionProfile.cs
aspnetcore/src/Repositories/FundingDecisionIndexRepository.cs
aspnetcore/src/Repositories/Maps/FundingCallProfile.cs
aspnetcore/src/Repositories/Maps/FundingDecisionProfile.cs
aspnetcore/src/Repositories/MemoryCacheKeys.cs
aspnetcore/src/Repositories/PublicationIndexRepository.cs
aspnetcore/src/Service.Models/FundingCall/FundingCall.cs
aspnetcore/src/Service.Models/FundingDecision/CallProgramme.cs
aspnetcore/src/Service.Models/FundingDecision/FrameworkProgramme.cs
aspnetcore/src/Service.Models/FundingDecision/FundingDecision.cs
aspnetcore/test/Indexer.Tests/Maps/FundingDecisionProfileTest.cs

fix: indexing for funding calls related to funding decisions

---

aspnetcore/src/ElasticService/ElasticSearchQueryGenerators/FundingDecisionQueryGenerator.cs
aspnetcore/src/Indexer/Indexer.cs
aspnetcore/src/Repositories/FundingCallIndexRepository.cs
aspnetcore/src/Repositories/FundingDecisionIndexRepository.cs
aspnetcore/src/Repositories/FundingDecisisionRepository.cs
aspnetcore/src/Repositories/IndexRepositoryBase.cs
aspnetcore/src/Repositories/InfrastructureIndexRepository.cs
aspnetcore/src/Repositories/Maps/FundingDecisionProfile.cs
aspnetcore/src/Repositories/Maps/OrganizationProfile.cs
aspnetcore/src/Repositories/MemoryCacheKeys.cs
aspnetcore/src/Repositories/OrganizationIndexRepository.cs
aspnetcore/src/Repositories/PublicationIndexRepository.cs
aspnetcore/src/Repositories/ResearchDatasetIndexRepository.cs
aspnetcore/src/Service.Models/FundingDecision/FundingDecision.cs
aspnetcore/src/Service.Models/FundingDecision/FundingGroupPerson.cs
aspnetcore/src/Service.Models/FundingDecision/FundingReceiver.cs
aspnetcore/src/Service.Models/FundingDecision/Organization.cs
aspnetcore/src/Service.Models/FundingDecision/OrganizationConsortium.cs
aspnetcore/src/Service.Models/Organization/Organization.cs
aspnetcore/test/Indexer.Tests/Maps/FundingDecisionProfileTest.cs
aspnetcore/test/Interface.Tests/Maps/FundingDecisionProfileTest.cs
aspnetcore/test/Repository.Tests/ResearchDatasetIndexRepositoryTest.cs

CSCTTV-3281 fixes to funding receivers

---

aspnetcore/src/Repositories/FundingCallIndexRepository.cs

DimCallProgramme must have both date properties or it must be of type continuous application

DimCallProgramme must have both date properties or continuous application

---

.vscode/launch.json
aspnetcore/openshift/api/rahti2/Dockerfile
aspnetcore/openshift/indexer/rahti2/Dockerfile
aspnetcore/src/ApiModels/ApiModels.csproj
aspnetcore/src/DatabaseContext/DatabaseContext.csproj
aspnetcore/src/ElasticService/ElasticService.csproj
aspnetcore/src/Exporter/Exporter.csproj
aspnetcore/src/Indexer/Indexer.csproj
aspnetcore/src/Interface/Interface.csproj
aspnetcore/src/Logging/Logging.csproj
aspnetcore/src/Repositories/Repositories.csproj
aspnetcore/src/Service.Models/Service.Models.csproj
aspnetcore/test/Indexer.Tests/Indexer.Tests.csproj
aspnetcore/test/Interface.Tests/Interface.Tests.csproj
aspnetcore/test/Repository.Tests/Repository.Tests.csproj

Upgrade from .NET6 to .NET8. Upgrade dependencies.

CSCTTV-3776 .NET8

---

aspnetcore/src/DatabaseContext/ApiDbContext.cs
aspnetcore/src/DatabaseContext/Entities/DimPublication.cs
aspnetcore/src/Indexer/Program.cs

Handle database change: added new field dim_publication_id in table dim_publication

Ttv model update 2024-09-19

---

aspnetcore/src/ApiModels/Publication/Publication.cs
aspnetcore/src/ApiModels/Query/GetPublicationsQueryParameters.cs
aspnetcore/src/ElasticService/ElasticSearchQueryGenerators/PublicationQueryGenerator.cs
aspnetcore/src/ElasticService/SearchParameters/PublicationSearchParameters.cs
aspnetcore/src/Repositories/Maps/PublicationProfile.cs
aspnetcore/src/Repositories/PublicationIndexRepository.cs
aspnetcore/src/Service.Models/Publication/OrgPublicationDTO.cs
aspnetcore/src/Service.Models/Publication/Publication.cs
aspnetcore/test/Indexer.Tests/Maps/PublicationProfileTest.cs
aspnetcore/test/Interface.Tests/Maps/PublicationProfileTest.cs

Co-publication handling
- Add search parameter ShowOrganisationPartofCoPublication
- Add search parameter HideCoPublications
- Modify logic of how authors and organizations related to publication are collected during indexing

CSCTTV-4013 co-publication handling

---

aspnetcore/src/Repositories/Maps/PublicationProfile.cs
aspnetcore/src/Repositories/PublicationIndexRepository.cs
aspnetcore/src/Service.Models/Publication/OrgPublicationArtPublicatonTypeCategoryDTO.cs
aspnetcore/src/Service.Models/Publication/OrgPublicationDatabaseContributionDTO.cs
aspnetcore/src/Service.Models/Publication/OrgPublicationFieldsOfArtDTO.cs
aspnetcore/src/Service.Models/Publication/OrgPublicationFieldsOfScienceDTO copy.cs
aspnetcore/src/Service.Models/Publication/OrgPublicationKeywordDTO.cs
aspnetcore/src/Service.Models/Publication/Publication.cs
aspnetcore/test/Indexer.Tests/Maps/PublicationProfileTest.cs

Collect copublication data from tables
- fact_dim_referencedata_field_of_science
- fact_dim_referencedata_field_of_art
- br_keyword_dim_publication
- br_artpublication_typecategory

CSCTTV-4013 co-publication handling fixes

---

aspnetcore/src/ApiModels/Query/GetVirtaQueryParameters.cs
aspnetcore/src/ApiModels/Query/VirtaPaginationQueryParameters.cs
aspnetcore/src/Interface/Controllers/DuplikaatitController.cs
aspnetcore/src/Interface/Controllers/ResponseHelper.cs
aspnetcore/src/Interface/Controllers/TilanneraporttiController.cs
aspnetcore/src/Interface/Controllers/VirheraporttiController.cs
aspnetcore/src/Interface/Controllers/VirtaJulkaisutietopalveluController.cs
aspnetcore/src/Interface/Controllers/YhteisjulkaisutRistiriitaisetController.cs
aspnetcore/src/Interface/Interface.csproj
aspnetcore/src/Interface/Interface.sln
aspnetcore/src/Interface/Models/Duplikaatit.cs
aspnetcore/src/Interface/Models/TableTest.cs
aspnetcore/src/Interface/Models/Testief.cs
aspnetcore/src/Interface/Models/Tilanneraportti.cs
aspnetcore/src/Interface/Models/Virheraportti.cs
aspnetcore/src/Interface/Models/YhteisjulkaisutRistiriitaiset.cs
aspnetcore/src/Interface/Program.cs
aspnetcore/src/Interface/VirtaJtpDbContext.cs

Virta report apis added to TTV publicAPI

Cscttv 3834 virta report apis 

---

aspnetcore/src/ApiModels/Query/GetVirtaQueryParameters.cs
aspnetcore/src/ApiModels/Query/VirtaPaginationQueryParameters.cs
aspnetcore/src/Interface/Controllers/DuplikaatitController.cs
aspnetcore/src/Interface/Controllers/ResponseHelper.cs
aspnetcore/src/Interface/Controllers/TilanneraporttiController.cs
aspnetcore/src/Interface/Controllers/VirheraporttiController.cs
aspnetcore/src/Interface/Controllers/VirtaJulkaisutietopalveluController.cs
aspnetcore/src/Interface/Controllers/YhteisjulkaisutRistiriitaisetController.cs
aspnetcore/src/Interface/Interface.csproj
aspnetcore/src/Interface/Interface.sln
aspnetcore/src/Interface/Models/Duplikaatit.cs
aspnetcore/src/Interface/Models/TableTest.cs
aspnetcore/src/Interface/Models/Testief.cs
aspnetcore/src/Interface/Models/Tilanneraportti.cs
aspnetcore/src/Interface/Models/Virheraportti.cs
aspnetcore/src/Interface/Models/YhteisjulkaisutRistiriitaiset.cs
aspnetcore/src/Interface/Program.cs
aspnetcore/src/Interface/VirtaJtpDbContext.cs

Virta report apis added to TTV publicAPI

Cscttv 3834 virta report apis

---

aspnetcore/src/Repositories/FundingDecisionIndexRepository.cs

researchfiUrl is not added to fundingDecision it typeOfFunding is 62, 66 or 69

CSCTTV-4183 researchfiUrl modification for fundingDecisions

---

aspnetcore/src/ElasticService/ElasticSearchExtensions.cs
aspnetcore/src/ElasticService/ElasticService.csproj
aspnetcore/src/Service.Models/Service.Models.csproj

Upgrade NEST client version. Enable compatibility mode for Elasticsearch 8

CSCTTV-3916 Upgrade NEST client. Enable compatibility mode. 

---

aspnetcore/src/DatabaseContext/ApiDbContext.cs
aspnetcore/src/DatabaseContext/Entities/DimCallDecision.cs
aspnetcore/src/DatabaseContext/Entities/DimDescriptiveItem.cs
aspnetcore/src/DatabaseContext/Entities/DimFundingDecision.cs
aspnetcore/src/DatabaseContext/Entities/DimOrganization.cs
aspnetcore/src/DatabaseContext/Entities/DimPublication.cs
aspnetcore/src/DatabaseContext/Entities/DimResearchProject.cs
aspnetcore/src/DatabaseContext/Entities/FactFieldValuesTest.cs
aspnetcore/src/Repositories/Maps/PublicationProfile.cs
aspnetcore/src/Repositories/PublicationIndexRepository.cs
aspnetcore/src/Service.Models/Publication/Publication.cs
aspnetcore/test/Indexer.Tests/Maps/PublicationProfileTest.cs
aspnetcore/test/Interface.Tests/FundingCallSystemTest.cs
aspnetcore/test/Repository.Tests/PublicationIndexRepositoryTest.cs

TTV database model update 2025_03
Move from dim_publication to dim_pid
- doi
- isbn
- issn
Rename in dim_publication
- parent_publication_publisher => parent_publication_editors
Remove several fields from dim_publication

CSCTTV-4277 TTV model update 2025_03
